name: Smily
favicon: null
layout_spectrum: 0.4759774222038686
typography_spectrum: 0.8822077340446413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a60b17'
    - '#ff807d'
    - '#ff3541'
    - '#0e0202'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
