typography_spectrum: 0.8822077340446413
color:
  brandColors:
    - '#ffffff'
    - '#a60b17'
    - '#ff807d'
    - '#ff3541'
    - '#0e0202'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4759774222038686
analytics:
  google: null
  facebook: null
  twitter: null
name: Smily
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Mes aventures
    id: a86e6eec-8cd2-4bc8-80d2-b7edadd5de30
    type: content
  - name: Ma vie en Afrique
    id: c2680a34-602f-4a33-8fd2-04b23c67280e
    type: content
  - name: A l'école
    id: 2ea949b3-6cc7-4345-8ce9-3d97e7b35e3f
    type: content
favicon: null
purpose: []
