name: Smily
favicon: null
layout_spectrum: 0.4759774222038686
typography_spectrum: 0.8822077340446413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23567476449534297
  lightness: 0.4088153827469796
  saturation: 0.9718232238665223
  rhythmicContrast: 0.9732671263627708
purpose: []
